name: "Check condition"
author: Phil A.
description: "Simply check if a condition is met"
branding:
  icon: check
  color: purple
inputs:
  success:
    description: "Succeed if 'true', fail if 'false'"
    required: true
runs:
  using: "composite"
  steps:
    - run: exit
      uses: actions/github-script@v3
      with:
        script: |
          if (!${{ inputs.success }}) {
            core.setFailed('Check failed')
          }
