name: Integration tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Integration test 1
        uses: ./
        with:
          success: true
      - name: Integration test 2
        uses: ./
        with:
          success: "true"
      - name: Integration test 3
        uses: ./
        with:
          success: ${{ 'a' == 'a' }}
      - name: Integration test 4
        id: t4
        uses: ./
        with:
          success: false
        continue-on-error: true
      - name: Integration test 4 check
        run: if [[ ${{ steps.t4.outcome }} == 'failure' ]]; then exit 0; else exit 1
      - name: Integration test 5
        uses: ./
        with:
          success: "false"
        continue-on-error: true
      - name: Integration test 5 check
        run: if [[ ${{ steps.t5.outcome }} == 'failure' ]]; then exit 0; else exit 1
      - name: Integration test 6
        uses: ./
        with:
          success: ${{ 'a' == 'b' }}
        continue-on-error: true
      - name: Integration test 6 check
        run: if [[ ${{ steps.t6.outcome }} == 'failure' ]]; then exit 0; else exit 1
