name: Integration tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Integration test 1
        uses: ./
        with:
          success: true
      - name: Integration test 2
        uses: ./
        with:
          success: "true"
      - name: Integration test 3
        uses: ./
        with:
          success: ${{ 'a' == 'a' }}
